FROM node:20.13.1-bullseye

# ARG LOGGER_LEVEL_ARG
# ARG DB_IP_ARG
# ARG DB_PORT_ARG
# ARG DB_NAME_ARG
# ARG DB_PASSWORD_ARG
# ARG DB_USERNAME_ARG
# ARG PORT_ARG
# ARG FRONTEND_IP_ARG
# ARG FRONTEND_PORT_ARG
# ARG JWT_SECRET_KEY_ARG

ENV LOGGER_LEVEL=$LOGGER_LEVEL
ENV DB_IP=$DB_IP
ENV DB_PORT=$DB_PORT
ENV DB_NAME=$DB_NAME
ENV DB_PASSWORD=$DB_PASSWORD
ENV DB_USERNAME=$DB_USERNAME
ENV PORT=$PORT
ENV FRONTEND_IP=$FRONTEND_IP
ENV FRONTEND_PORT=$FRONTEND_PORT
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY

WORKDIR /

COPY src src
COPY package.json package.json
COPY package-lock.json package-lock.json
COPY configs configs
COPY tsconfig.json tsconfig.json

RUN npm clean-install
RUN npm run build

EXPOSE $PORT

ENTRYPOINT ["npm", "start"]
